import Sidebar from "@/components/sidebar/Sidebar";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" suppressHydrationWarning>
      <body className={`${inter.className} flex flex-row overflow-hidden`}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem={true}>
          <Sidebar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
